### ISSUE TITLE
Feature: Example Config page

### ISSUE THREAD

**Issue by jxsl13** [Tardo/twp#38]
It would be nice to have next to the advanced config another tab where you can have an example config stored.

**Comment by CytraL** [comment]
Can you explain this? How this "example config" is created? Perhaps best an "duplicate" option?

**Comment by jxsl13** [comment]
I mean just a tab where the admin who added the modification can add a list
of all commands of the added mod, so that people configuring a server do
not need to search the web to configure a server.

Alexandre Díaz <notifications@github.com> schrieb am Sa., 4. März 2017,
21:11:

**Comment by CytraL** [comment]
Currently can extend the "configuration wizard" using an "config.json" file inside the folder of the mod.

https://github.com/CytraL/twp/wiki/How-extend-configuration-wizard

** Need update wiki... best example and python script for generate the .json from the sources.
